version: "3.8"

networks:
  chrsolr:
    driver: bridge

services:
  web_api:
    image: chrsolr-api:latest
    container_name: chrsolr-api-app
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mssql
    environment:
      DB_CONNECTION_STRING: Data Source=localhost; Database=chrsolr; User Id=SA; Password=S3CR3T_P8SS; MultipleActiveResultSets=true; TrustServerCertificate=True;
    ports:
      - 5080:80
    networks:
      - chrsolr

  mssql:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: sql_server2022
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: S3CR3T_P8SS
    ports:
      - 1433:1433
    volumes:
      - mssql_data:/var/lib/mssql_chrsolr/data
    networks:
      - chrsolr

volumes:
  mssql_data:
