version: "3.9"

networks:
  chrsolr-api:
    driver: bridge

services:
  web_api:
    image: chrsolr-api:latest
    container_name: chrsolr-api-app
    build:
      context: .
      dockerfile: Dockerfile.dev
    depends_on:
      - mssql
    environment:
      DB_CONNECTION_STRING: Data Source=sql_server2022; Database=chrsolr; User Id=SA; Password=S3CR3T_P8SS; MultipleActiveResultSets=true; TrustServerCertificate=True;
      ASPNETCORE_URLS: http://+:9000
      SHOW_SWAGGER: true
    ports:
      - 5080:9000
    networks:
      - chrsolr-api

  mssql:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: sql_server2022
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: S3CR3T_P8SS
    ports:
      - 1433:1433
    volumes:
      - sqlserver:/var/opt/mssql
    networks:
      - chrsolr-api

volumes:
  sqlserver:
